name: Java CI with Maven and Sonar

on: [push, pull_request]

jobs:

  build:
    name: build and test project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      env:
        WIT_CLIENT_TOKEN: ${{secrets.WIT_CLIENT_TOKEN}}


  sonar:
    name: analyze with sonarqube
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Run analysis
        run: >
          ./mvnw --batch-mode
          -Pcoverage
          clean verify
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=refactoring-bot
          -Dsonar.projectKey=de.refactoringBot:RefactoringBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
