name: Java CI with Maven and Sonar

on: [push, pull_request]

jobs:

  build:
    name: build and test project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      env:
        WIT_CLIENT_TOKEN: ${{secrets.WIT_CLIENT_TOKEN}}
    - name: analyze with sonarcloud
      if: github.ref == 'refs/heads/master'      
      run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false  
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
